### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by johnothwolo** [roonieone/Extractr#2]
macOS 10.12.4, it starts with a blank screen, and if I go full screen it goes black. I'm about to debug it on Xcode.

**Comment by roonieone** [comment]
Okay cool. If you find a fix, feel free to submit a PR. I'll probably deprecate this app soon because I don't see much need for it now that you can simply decompress IPSWs to see their contents, but if you want to add features or fix bugs, by all means please do.

**Comment by NoOne-dev** [comment]
The issue is your custom font, comment it out and the app works

**Comment by NoOne-dev** [comment]
There is still a need for it, and it works very well

**Comment by roonieone** [comment]
This project is now abandoned. See the [README](https://github.com/roonieone/Extractr/blob/master/README.md).
